##################
# Docker Compose #
##################

version: "3"

#####################
# Docker Containers #
#####################

services:
  ########
  # Node #
  ########

  node:
    # image: node:12-alpine // you can replace build with this image 
    build: ./docker
    working_dir: /root/app/src
    environment:
      - SERVER_PORT=${SERVER_PORT}
    env_file:
      - ./env/default
      - ./env/secrets
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/root/app
      - ~/.npm:/root/.npm
